### ISSUE TITLE
NoSuchMethodError at ByteStreamsHack.toByteArray(...)

### ISSUE THREAD

**Issue by Lanchon** [DexPatcher/multidexlib2#8]
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.io.ByteStreams.toByteArray(Ljava/io/InputStream;J)[B
	at com.google.common.io.ByteStreamsHack.toByteArray(ByteStreamsHack.java:30)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:54)
	at lanchon.multidexlib2.ZipFileDexContainer.<init>(ZipFileDexContainer.java:48)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:61)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:48)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:39)
```

reference: https://github.com/DexPatcher/multidexlib2/issues/7#issuecomment-700517253

**Comment by auermich93** [comment]
@Lanchon: Any intention to fix that issue in the near future? If I got it right, it's due to a transitive guava dependency that is too new/old and doesn't provide the respective method?
